apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: book-tracker
  labels:
    app.kubernetes.io/name: book-tracker
    app.kubernetes.io/component: database
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "bookadmin"
  MONGO_INITDB_ROOT_PASSWORD: "kiii"
  MONGO_URI: "mongodb://bookadmin:kiii@mongo:27017/booktracker?authSource=admin"