apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: book-tracker
  labels:
    app.kubernetes.io/name: book-tracker
    app.kubernetes.io/component: database
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: book-tracker
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: book-tracker
        app.kubernetes.io/component: database
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mongo
          image: mongo:7
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD


          volumeMounts:
            - name: data
              mountPath: /data/db

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping').ok"
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping').ok"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: book-tracker
          app.kubernetes.io/component: database
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi