apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: book-tracker
  labels:
    app.kubernetes.io/name: book-tracker
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: book-tracker
    app.kubernetes.io/component: database
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP